# Restart Nginx.
- name: Restart Nginx
  ansible.builtin.command: "{{item}}"
  loop:
    - "{{supervisor_client_path}} update nginx"
    - "{{supervisor_client_path}} restart nginx"
  vars:
    supervisor_client_path: "/usr/bin/supervisorctl"
  tags:
    - restart
