# Configure Nginx.
- name: Configure Nginx
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{server_conf_path}}"
    owner: root
    group: root
    mode: 0600
    backup: false
  vars:
    conf_dir: "{{nginx.conf_dir}}"
    system_dir: "{{nginx.system_dir}}"
    server_conf_path: "{{conf_dir}}/server.conf"
    pid_path: "{{system_dir}}/process.pid"
  tags:
    - configure

# Configure Nginx for App.
- name: Configure Nginx for App
  ansible.builtin.template:
    src: "{{stack}}/app.conf.j2"
    dest: "{{app_conf_path}}"
    owner: root
    group: root
    mode: 0600
    backup: false
  vars:
    stack: "{{nginx.stack}}"
    external_domain: "{{nginx.external_domain}}"
    log_dir: "{{nginx.log_dir}}"
    conf_dir: "{{nginx.conf_dir}}"
    app_source_dir: "{{app.source_dir}}"
    app_conf_path: "{{conf_dir}}/app.conf"
  tags:
    - configure

# Create empty PID file.
- name: Create empty PID file
  ansible.builtin.file:
    path: "{{server_pid_path}}"
    state: touch
    owner: root
    group: root
  vars:
    system_dir: "{{nginx.system_dir}}"
    server_pid_path: "{{system_dir}}/process.pid"
  tags:
    - configure

# Configure Supervisor for Nginx.
- name: Configure Supervisor for Nginx
  ansible.builtin.template:
    src: supervisor.ini.j2
    dest: "{{init_conf_path}}"
    owner: root
    group: root
    mode: 0600
    backup: false
  vars:
    system_dir: "{{nginx.system_dir}}"
    init_conf_path: "{{system_dir}}/supervisor.ini"
    server_pid_path: "{{system_dir}}/process.pid"
  tags:
    - configure

# Symlink Nginx server configuration.
- name: Symlink Nginx server configuration
  ansible.builtin.command:
    cmd: "ln -sf {{server_conf_path}} /etc/nginx/nginx.conf"
    removes: "{{server_conf_path}}"
  vars:
    conf_dir: "{{nginx.conf_dir}}"
    server_conf_path: "{{conf_dir}}/server.conf"
  tags:
    - configure

# Symlink Nginx configuration for App.
- name: Symlink Nginx configuration for App
  ansible.builtin.command:
    cmd: "ln -sf {{app_conf_path}} /etc/nginx/conf.d/app.conf"
    removes: "{{app_conf_path}}"
  vars:
    conf_dir: "{{nginx.conf_dir}}"
    app_conf_path: "{{conf_dir}}/app.conf"
  tags:
    - configure

# Symlink Supervisor configuration.
- name: Symlink Supervisor configuration
  ansible.builtin.command:
    cmd: "ln -sf {{init_conf_path}} {{supervisor_conf_dir}}/nginx.ini"
    removes: "{{init_conf_path}}"
  vars:
    system_dir: "{{nginx.system_dir}}"
    supervisor_conf_dir: "{{system.supervisor.conf_dir}}"
    init_conf_path: "{{system_dir}}/supervisor.ini"
  tags:
    - configure
