# Start Nginx.
- name: Start Nginx
  ansible.builtin.command:
    cmd: "{{item}}"
    removes: "{{init_conf_path}}"
  loop:
    - "{{supervisor_client_path}} update nginx"
    - "{{supervisor_client_path}} start nginx"
  vars:
    system_dir: "{{nginx.system_dir}}"
    supervisor_exec_dir: "{{system.supervisor.exec_dir}}"
    supervisor_client_path: "{{supervisor_exec_dir}}/supervisorctl"
    init_conf_path: "{{system_dir}}/supervisor.ini"
  tags:
    - start
