# Remove Postfix service.
- name: Remove Postfix service
  ansible.builtin.command:
    cmd: "{{item}}"
    removes: /sbin/postfix
  loop:
    - systemctl stop postfix.service
    - systemctl disable postfix.service
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup

# Remove Firewall service.
- name: Remove Firewall service
  ansible.builtin.command:
    cmd: "{{item}}"
    removes: /usr/sbin/firewalld
  loop:
    - systemctl stop firewalld.service
    - systemctl disable firewalld.service
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup

# Enable netfilter Linux kernel module.
- name: Enable netfilter Linux kernel module
  ansible.builtin.command:
    cmd: modprobe br_netfilter
    removes: /bin/systemd
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup

# Disable Linux swap memory.
- name: Disable Linux swap memory
  ansible.builtin.command: swapoff -a
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup

# Install Git.
- name: Install Git
  ansible.builtin.yum:
    name:
      - git
    state: present
  tags:
    - setup
