# Start Supervisor.
- name: Start Supervisor
  ansible.builtin.command:
    cmd: "{{system.supervisor.exec_dir}}/supervisord -c {{system.supervisor.conf_path}}"
    removes: "{{system.supervisor.conf_path}}"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 2
  tags:
    - start
