# Stop Supervisor.
- name: Stop Supervisor
  ansible.builtin.command:
    cmd: "{{system.supervisor.exec_dir}}/supervisorctl shutdown"
    removes: "{{system.supervisor.exec_dir}}/supervisorctl"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - stop
