# Stop Supervisor.
- name: Stop Supervisor
  ansible.builtin.command:
    cmd: "{{supervisor_client_path}} shutdown"
    removes: "{{supervisor_client_path}}"
  vars:
    supervisor_exec_dir: "{{system.supervisor.exec_dir}}"
    supervisor_client_path: "{{supervisor_exec_dir}}/supervisorctl"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - stop
