# Install Python.
- name: Install Python
  ansible.builtin.yum:
    name:
      - python-2.7.18
      - python-devel
      - python-pip
      - python-setuptools
    state: present
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - setup

# Create App directories.
- name: Create App directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    recurse: true
    mode: 0700
  loop:
    - "{{root_dir}}"
    - "{{source_dir}}"
    - "{{log_dir}}"
    - "{{script_dir}}"
    - "{{system_dir}}"
  vars:
    root_dir: "{{app.root_dir}}"
    source_dir: "{{app.source_dir}}"
    log_dir: "{{app.log_dir}}"
    script_dir: "{{app.script_dir}}"
    system_dir: "{{app.system_dir}}"
  tags:
    - setup
