# Start App.
- name: Start App
  ansible.builtin.command: "{{item}}"
  loop:
    - "{{supervisor_client_path}} update app"
    - "{{supervisor_client_path}} start app"
  vars:
    supervisor_client_path: "/usr/bin/supervisorctl"
  tags:
    - start
