# Fetch App Git repository.
- name: Fetch App Git repository
  ansible.builtin.git:
    repo: "{{repo_url}}"
    version: "{{revision}}"
    dest: "{{source_dir}}"
    update: yes
    force: yes
  vars:
    revision: "{{app.revision}}"
    source_dir: "{{app.source_dir}}"
    repo_url: "{{app.repo_url}}"
  tags:
    - update

# Install Python packages.
- name: Install Python packages
  ansible.builtin.command:
    cmd: "{{item}}"
    chdir: "{{source_dir}}"
  loop:
    - pip install certifi==2023.11.17
    - pip install urllib3==1.26.16
    - pip install MarkupSafe==2.1.3
    - pip install Jinja2==3.1.2
    - pip install flask==1.1.4
    - pip install flask==2.2.5
    - pip install redis==2.10.6
    - pip install elastic-apm[flask]==3.0.5
  vars:
    source_dir: "{{app.source_dir}}"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  tags:
    - update
