# Fetch App Git repository.
- name: Fetch App Git repository
  ansible.builtin.git:
    repo: "{{repo_url}}"
    version: "{{revision}}"
    dest: "{{source_dir}}"
    update: yes
    force: yes
  vars:
    revision: "{{app.revision}}"
    source_dir: "{{app.source_dir}}"
    repo_url: "{{app.repo_url}}"
  tags:
    - update

# Install App Python packages.
- name: Install App Python packages
  ansible.builtin.command: pip install "{{item}}"
  args:
    chdir: "{{source_dir}}"
  loop:
    - certifi==2023.11.17
    - urllib3==1.26.16
    - MarkupSafe==2.1.3
    - Jinja2==3.1.2
    - flask==2.2.5
    - redis==2.10.6
    - elastic-apm[flask]==3.0.5
  vars:
    source_dir: "{{app.source_dir}}"
  tags:
    - update
