# Apply required Linux kernel params.
- name: Apply required Linux kernel params
  ansible.builtin.command: "sysctl -p /etc/sysctl.d/90-{{system.organization}}.conf"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
    - status.rc != 255
  tags:
    - configure
