# Configure Redis.
- name: Configure Redis
  template:
    src: server.conf.j2
    dest: "{{redis.conf_dir}}/redis.conf"
    owner: root
    group: root
    mode: 0600
  tags:
    - configure

# Create empty PID file.
- name: Create empty PID file
  file:
    path: "{{redis.system_dir}}/process.pid"
    state: touch
    owner: root
    group: root
    mode: 0600
  tags:
    - configure

# Configure Supervisor for Redis.
- name: Configure Supervisor for Redis
  template:
    src: supervisor.ini.j2
    dest: "{{redis.system_dir}}/supervisor.ini"
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart Redis
  tags:
    - configure

# Symlink Supervisor configuration.
- name: Symlink Supervisor configuration
  command: "ln -sf {{redis.system_dir}}/supervisor.ini /etc/supervisord.d/redis.ini"
  tags:
    - configure
