# Install system packages.
- name: Install system packages
  ansible.builtin.yum:
    name:
      - tcl
    state: present
  tags:
    - setup

# Download and extract Redis.
- name: Download and extract Redis
  ansible.builtin.unarchive:
    src: http://download.redis.io/releases/redis-{{redis.release_version}}.tar.gz
    dest: /tmp
    owner: root
    group: root
    remote_src: yes
    creates: /tmp/redis-{{redis.release_version}}
  tags:
    - setup

# Compile and install Redis.
- name: Compile and install Redis
  ansible.builtin.command: "{{item}}"
  register: status
  failed_when:
    - status.rc != 0
    - status.rc != 1
  args:
    chdir: "{{source_dir}}"
  loop:
    - make distclean
    - make
    - make install
  vars:
    source_dir: "/tmp/redis-{{redis.release_version}}"
  tags:
    - setup

# Cleanup source.
- name: Cleanup source
  ansible.builtin.file:
    path: /tmp/redis-{{redis.release_version}}
    state: absent
    owner: root
    group: root
    mode: 0700
  tags:
    - setup

# Create Redis directories.
- name: Create Redis directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    recurse: true
    mode: 0700
  loop:
    - "{{redis.root_dir}}"
    - "{{redis.data_dir}}"
    - "{{redis.log_dir}}"
    - "{{redis.conf_dir}}"
    - "{{redis.script_dir}}"
    - "{{redis.system_dir}}"
  tags:
    - setup
